version: '3'

services:

  # Proxy for ssl termination and easier hostname access
  # SSL certificates with the virtual host name need to be added to ./data/ssl
  proxy:
    image: ghcr.io/juliushaertl/nextcloud-dev-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/ssl/:/etc/nginx/certs
    environment:
      DHPARAM_BITS: 2048
      DHPARAM_GENERATION: "false"
      HTTPS_METHOD: "noredirect"
      HSTS: "off"
    cap_add:
      - SYS_ADMIN
    networks:
      default:
        aliases:
          - nextcloud${DOMAIN_SUFFIX}
          - nextcloud2${DOMAIN_SUFFIX}
          - nextcloud3${DOMAIN_SUFFIX}
          - stable16${DOMAIN_SUFFIX}
          - stable17${DOMAIN_SUFFIX}
          - stable18${DOMAIN_SUFFIX}
          - stable19${DOMAIN_SUFFIX}
          - stable20${DOMAIN_SUFFIX}
          - stable21${DOMAIN_SUFFIX}
          - stable22${DOMAIN_SUFFIX}
          - stable23${DOMAIN_SUFFIX}
          - collabora${DOMAIN_SUFFIX}
          - onlyoffice${DOMAIN_SUFFIX}
          - proxy${DOMAIN_SUFFIX}
          - hpb${DOMAIN_SUFFIX}
          - push${DOMAIN_SUFFIX}
          - keycloak${DOMAIN_SUFFIX}
          - portal${DOMAIN_SUFFIX}
          - gs1${DOMAIN_SUFFIX}
          - gs2${DOMAIN_SUFFIX}
          - lookup${DOMAIN_SUFFIX}

  haproxy:
    image: haproxy
    expose:
      - 80
    environment:
      VIRTUAL_HOST: "proxy${DOMAIN_SUFFIX}"
    volumes:
      - ./docker/configs/haproxy.conf:/usr/local/etc/haproxy/haproxy.cfg:ro

  nextcloud:
    image: ghcr.io/juliushaertl/nextcloud-dev-php${PHP_VERSION:-74}:latest
    environment:
      SQL: ${SQL:-mysql}
      NEXTCLOUD_AUTOINSTALL: "YES"
      NEXTCLOUD_AUTOINSTALL_APPS:
      WITH_REDIS: "YES"
      VIRTUAL_HOST: "nextcloud${DOMAIN_SUFFIX}"
      ADDITIONAL_APPS_PATH:
      NEXTCLOUD_TRUSTED_DOMAINS:
    volumes:
      - '${REPO_PATH_SERVER:-/home/jus/repos/nextcloud/server}:/var/www/html'
      - data:/var/www/html/data
      - config:/var/www/html/config
      - '${ADDITIONAL_APPS_PATH:-./data/apps-extra}:/var/www/html/apps-extra'
      - /var/www/html/apps-writable
      - ./data/skeleton/:/skeleton
      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
      - ./data/shared:/shared
    ports:
      - "${PORTBASE:-800}0:80"
    depends_on:
      - ${DB_SERVICE:-database-mysql}
      - redis
      - mail
    extra_hosts:
      - host.docker.internal:host-gateway

  nextcloud2:
    image: ghcr.io/juliushaertl/nextcloud-dev-php${PHP_VERSION:-73}:latest
    environment:
      SQL: 'mysql'
      VIRTUAL_HOST: "nextcloud2${DOMAIN_SUFFIX}"
    volumes:
      - '${REPO_PATH_SERVER:-/home/jus/repos/nextcloud/server}:/var/www/html'
      - '${ADDITIONAL_APPS_PATH:-./data/apps-extra}:/var/www/html/apps-extra'
      - ./data/skeleton/:/skeleton
      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
    ports:
      - "${PORTBASE:-800}1:80"
    depends_on:
      - database-mysql
      - redis
      - mail
    extra_hosts:
      - host.docker.internal:host-gateway

  nextcloud3:
    image: ghcr.io/juliushaertl/nextcloud-dev-php${PHP_VERSION:-73}:latest
    environment:
      SQL: 'mysql'
      VIRTUAL_HOST: "nextcloud3${DOMAIN_SUFFIX}"
    volumes:
      - '${REPO_PATH_SERVER:-/home/jus/repos/nextcloud/server}:/var/www/html'
      - '${ADDITIONAL_APPS_PATH:-./data/apps-extra}:/var/www/html/apps-extra'
      - ./data/skeleton/:/skeleton
      - ./docker/configs/config.php:/var/www/html/config/writable.config.php:ro
      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
    depends_on:
      - database-mysql
      - redis
      - mail
    extra_hosts:
      - host.docker.internal:host-gateway

  stable16:
    image: ghcr.io/juliushaertl/nextcloud-dev-php${PHP_VERSION:-72}:latest
    environment:
      SQL: 'sqlite'
      NEXTCLOUD_AUTOINSTALL: "YES"
      NEXTCLOUD_AUTOINSTALL_APPS:
      WITH_REDIS: "YES"
      VIRTUAL_HOST: stable16${DOMAIN_SUFFIX}
      ADDITIONAL_APPS_PATH:
      NEXTCLOUD_TRUSTED_DOMAINS:
    volumes:
      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/stable16:/var/www/html'
      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/stable16/apps-extra:/var/www/html/apps-extra'
      - /var/www/html/data
      - /var/www/html/config
      - /var/www/html/apps-writable
      - ./data/skeleton/:/skeleton
      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
    depends_on:
      - redis
      - mail
    extra_hosts:
      - host.docker.internal:host-gateway

  stable17:
    image: ghcr.io/juliushaertl/nextcloud-dev-php${PHP_VERSION:-72}:latest
    environment:
      SQL: 'sqlite'
      NEXTCLOUD_AUTOINSTALL: "YES"
      NEXTCLOUD_AUTOINSTALL_APPS:
      WITH_REDIS: "YES"
      VIRTUAL_HOST: stable17${DOMAIN_SUFFIX}
      ADDITIONAL_APPS_PATH:
      NEXTCLOUD_TRUSTED_DOMAINS:
    volumes:
      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/stable17:/var/www/html'
      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/stable17/apps-extra:/var/www/html/apps-extra'
      - /var/www/html/data
      - /var/www/html/config
      - /var/www/html/apps-writable
      - ./data/skeleton/:/skeleton
      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
    depends_on:
      - redis
      - mail
    extra_hosts:
      - host.docker.internal:host-gateway

  stable18:
    image: ghcr.io/juliushaertl/nextcloud-dev-php${PHP_VERSION:-73}:latest
    environment:
      SQL: 'sqlite'
      NEXTCLOUD_AUTOINSTALL: "YES"
      NEXTCLOUD_AUTOINSTALL_APPS:
      WITH_REDIS: "YES"
      VIRTUAL_HOST: stable18${DOMAIN_SUFFIX}
      ADDITIONAL_APPS_PATH:
      NEXTCLOUD_TRUSTED_DOMAINS:
    volumes:
      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/stable18:/var/www/html'
      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/stable18/apps-extra:/var/www/html/apps-extra'
      - /var/www/html/data
      - /var/www/html/config
      - /var/www/html/apps-writable
      - ./data/skeleton/:/skeleton
      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
    ports:
      - "${PORTBASE:-800}0:80"
    depends_on:
      - redis
      - mail
    extra_hosts:
      - host.docker.internal:host-gateway

  stable19:
    image: ghcr.io/juliushaertl/nextcloud-dev-php${PHP_VERSION:-72}:latest
    environment:
      SQL: 'sqlite'
      NEXTCLOUD_AUTOINSTALL: "YES"
      NEXTCLOUD_AUTOINSTALL_APPS:
      WITH_REDIS: "YES"
      VIRTUAL_HOST: stable19${DOMAIN_SUFFIX}
      ADDITIONAL_APPS_PATH:
      NEXTCLOUD_TRUSTED_DOMAINS:
    volumes:
      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/stable19:/var/www/html'
      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/stable19/apps-extra:/var/www/html/apps-extra'
      - ./data/skeleton/:/skeleton
      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
    depends_on:
      - redis
      - mail
    extra_hosts:
      - host.docker.internal:host-gateway

  stable20:
    image: ghcr.io/juliushaertl/nextcloud-dev-php${PHP_VERSION:-72}:latest
    environment:
      SQL: 'sqlite'
      NEXTCLOUD_AUTOINSTALL: "YES"
      NEXTCLOUD_AUTOINSTALL_APPS:
      WITH_REDIS: "YES"
      VIRTUAL_HOST: stable20${DOMAIN_SUFFIX}
      ADDITIONAL_APPS_PATH:
      NEXTCLOUD_TRUSTED_DOMAINS:
    volumes:
      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/stable20:/var/www/html'
      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/stable20/apps-extra:/var/www/html/apps-extra'
      - ./data/skeleton/:/skeleton
      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
    depends_on:
      - redis
      - mail
    extra_hosts:
      - host.docker.internal:host-gateway

  stable21:
    image: ghcr.io/juliushaertl/nextcloud-dev-php${PHP_VERSION:-73}:latest
    environment:
      SQL: 'sqlite'
      NEXTCLOUD_AUTOINSTALL: "YES"
      NEXTCLOUD_AUTOINSTALL_APPS:
      WITH_REDIS: "YES"
      VIRTUAL_HOST: stable21${DOMAIN_SUFFIX}
      ADDITIONAL_APPS_PATH:
      NEXTCLOUD_TRUSTED_DOMAINS:
    volumes:
      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/stable21:/var/www/html'
      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/stable21/apps-extra:/var/www/html/apps-extra'
      - ./data/skeleton/:/skeleton
      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
    depends_on:
      - redis
      - mail
    extra_hosts:
      - host.docker.internal:host-gateway

  stable22:
    image: ghcr.io/juliushaertl/nextcloud-dev-php${PHP_VERSION:-73}:latest
    environment:
      SQL: 'sqlite'
      NEXTCLOUD_AUTOINSTALL: "YES"
      NEXTCLOUD_AUTOINSTALL_APPS:
      WITH_REDIS: "YES"
      VIRTUAL_HOST: stable22${DOMAIN_SUFFIX}
      ADDITIONAL_APPS_PATH:
      NEXTCLOUD_TRUSTED_DOMAINS:
    volumes:
      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/stable22:/var/www/html'
      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/stable22/apps-extra:/var/www/html/apps-extra'
      - /var/www/html/data
      - /var/www/html/config
      - /var/www/html/apps-writable
      - ./data/skeleton/:/skeleton
      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
    depends_on:
      - redis
      - mail
    extra_hosts:
      - host.docker.internal:host-gateway

  stable23:
    image: ghcr.io/juliushaertl/nextcloud-dev-php${PHP_VERSION:-73}:latest
    environment:
      SQL: 'sqlite'
      NEXTCLOUD_AUTOINSTALL: "YES"
      NEXTCLOUD_AUTOINSTALL_APPS:
      WITH_REDIS: "YES"
      VIRTUAL_HOST: stable23${DOMAIN_SUFFIX}
      ADDITIONAL_APPS_PATH:
      NEXTCLOUD_TRUSTED_DOMAINS:
    volumes:
      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/stable23:/var/www/html'
      - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/stable23/apps-extra:/var/www/html/apps-extra'
      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
    depends_on:
      - redis
      - mail
    extra_hosts:
      - host.docker.internal:host-gateway

  database-mysql:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: 'nextcloud'
      MYSQL_PASSWORD: 'nextcloud'
      MYSQL_USER: 'nextcloud'
      MYSQL_DATABASE: 'nextcloud'
    ports:
      - "${PORTBASE:-800}2:3306"
    volumes:
      - mysql:/var/lib/mysql

  database-postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql

  redis:
    image: redis:6

  ldap:
    image: osixia/openldap
    command: --copy-service --loglevel debug
    expose:
      - 389
      - 636
    ports:
      - 3389:389
    environment:
      LDAP_DOMAIN: planetexpress.com
      LDAP_BASE_DN: dc=planetexpress,dc=com
    volumes:
      - ./data/ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom

  phpmyadmin:
    image: phpmyadmin
    environment:
      VIRTUAL_HOST: "phpmyadmin${DOMAIN_SUFFIX}"
      PMA_ARBITRARY: 1
      PMA_HOST: database-mysql
      PMA_USER: root
      PMA_PASSWORD: nextcloud

  ldapadmin:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: 'false'
    ports:
      - "${PORTBASE:-800}8:80"

  saml:
    image: unicon/simplesamlphp
    volumes:
      - ./docker/configs/var-simplesamlphp/config:/var/simplesamlphp/config
      - ./docker/configs/var-simplesamlphp/cert:/var/simplesamlphp/cert
      - ./docker/configs/var-simplesamlphp/metadata:/var/simplesamlphp/metadata
    environment:
      VIRTUAL_HOST: "sso${DOMAIN_SUFFIX}"
    expose:
      - 80

  mail:
    image: ghcr.io/juliushaertl/nextcloud-dev-mailhog:latest
    environment:
      VIRTUAL_HOST: "mail${DOMAIN_SUFFIX}"
      VIRTUAL_PORT: 8025

  smb:
    image: dperson/samba
    ports:
      - 139
      - 445
    environment:
      # -u "<username;password>[;ID;group;GID]"
      USER: "admin;admin"
      USER2: "user1;user1"
      USER3: "user2;user2"
      # -s "<name;/path>[;browse;readonly;guest;users;admins;writelist;comment]"
      SHARE: "public;/smbmount;yes;no;yes;all;admin;admin"
      SHARE2: "user1;/smb/user1;yes;no;no;user1"
      SHARE3: "user2;/smb/user2;yes;no;no;user2"
    volumes:
      - smb:/smbmount
      - smbhomes:/smb

  blackfire:
    image: blackfire/blackfire:2
    ports:
      - 8707:8307
    environment:
      - BLACKFIRE_SERVER_ID
      - BLACKFIRE_SERVER_TOKEN

  collabora:
    image: collabora/code:latest
    expose:
      - 9980
    cap_add:
      - MKNOD
    environment:
      domain: nextcloud${DOMAIN_SUFFIX}|.*.local.dev.bitgrid.net
      dictionaries: de_DE en_US en_GB
      username: admin
      password: admin
      VIRTUAL_HOST: collabora${DOMAIN_SUFFIX}
      VIRTUAL_PORT: 9980
      VIRTUAL_PROTO: http
      extra_params: "--o:ssl.enable=false"

  onlyoffice:
    image: onlyoffice/documentserver-ee:latest
    environment:
      VIRTUAL_HOST: onlyoffice${DOMAIN_SUFFIX}
    expose:
      - '80'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice

  minio:
    image: minio/minio
    environment:
      VIRTUAL_HOST: minio${DOMAIN_SUFFIX}
      MINIO_ACCESS_KEY: nextcloud
      MINIO_SECRET_KEY: nextcloud
    ports:
      - "${PORTBASE:-800}5:9000"
    volumes:
      - objectstorage_minio:/data
    command: server /data

  elasticsearch:
    build:
      context: ./docker
      dockerfile: Dockerfile.elasticsearch
    environment:
      discovery.type: single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  push:
    image: icewind1991/notify_push
    ports:
      - '8191:80'
    environment:
      RUST_LOG: debug
      VIRTUAL_HOST: push${DOMAIN_SUFFIX}
      VIRTUAL_PORT: 8191
      DATABASE_URL: mysql://nextcloud:nextcloud@master_database-mysql_1/nextcloud
      REDIS_URL: redis://redis
      NEXTCLOUD_URL: https://nextcloud.local.dev.bitgrid.net

  keycloak:
    image: quay.io/keycloak/keycloak:13.0.1
    expose:
      - 8080
    volumes:
      - ./docker/configs/keycloak:/tmp/keycloak
    environment:
      VIRTUAL_HOST: "keycloak${DOMAIN_SUFFIX}"
      VIRTUAL_PORT: 8080
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_IMPORT: /tmp/keycloak/realm-export.json

  av:
    image: mkodockx/docker-clamav:alpine
    container_name: nextav
    restart: unless-stopped
    volumes:
      - clam:/var/lib/clamav

  portal:
    image: ghcr.io/juliushaertl/nextcloud-dev-php${PHP_VERSION:-73}:latest
    environment:
      VIRTUAL_HOST: portal${DOMAIN_SUFFIX}
      SQL: 'mysql'
      GS_MODE: master
    volumes:
      - '${REPO_PATH_SERVER:-/home/jus/repos/nextcloud/server}:/var/www/html'
      - '${ADDITIONAL_APPS_PATH:-./data/apps-extra}:/var/www/html/apps-extra'
      - ./data/skeleton/:/skeleton
      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
    depends_on:
      - redis
      - mail
    extra_hosts:
      - host.docker.internal:host-gateway

  gs1:
    image: ghcr.io/juliushaertl/nextcloud-dev-php${PHP_VERSION:-73}:latest
    environment:
      VIRTUAL_HOST: gs1${DOMAIN_SUFFIX}
      SQL: 'mysql'
      GS_MODE: slave
    volumes:
      - '${REPO_PATH_SERVER:-/home/jus/repos/nextcloud/server}:/var/www/html'
      - '${ADDITIONAL_APPS_PATH:-./data/apps-extra}:/var/www/html/apps-extra'
      - ./data/skeleton/:/skeleton
      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
    depends_on:
      - redis
      - mail
    extra_hosts:
      - host.docker.internal:host-gateway

  gs2:
    image: ghcr.io/juliushaertl/nextcloud-dev-php${PHP_VERSION:-73}:latest
    environment:
      VIRTUAL_HOST: gs2${DOMAIN_SUFFIX}
      SQL: 'mysql'
      GS_MODE: slave
    volumes:
      - '${REPO_PATH_SERVER:-/home/jus/repos/nextcloud/server}:/var/www/html'
      - '${ADDITIONAL_APPS_PATH:-./data/apps-extra}:/var/www/html/apps-extra'
      - ./data/skeleton/:/skeleton
      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
    depends_on:
      - redis
      - mail
    extra_hosts:
      - host.docker.internal:host-gateway

  lookup:
    image: ghcr.io/juliushaertl/nextcloud-dev-lookupserver:latest
    environment:
      VIRTUAL_HOST: "lookup${DOMAIN_SUFFIX}"
    # volumes:
    #  - '${STABLE_ROOT_PATH:-/home/jus/repos/nextcloud}/lookupserver:/var/www/html'
    extra_hosts:
      - host.docker.internal:host-gateway

  previews_hpb:
    image: h2non/imaginary
    ports:
      - "8088:8088"
    environment:
      - PORT=8088


volumes:
  data:
  config:
  mysql:
  postgres:
  data2:
  config2:
  document_data:
  document_log:
  objectstorage_minio:
  smb:
  smbhomes:
  elasticsearch_data:
  clam:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET:-192.168.21.0/24}
